version: '3.10'
services:
  app-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONNECTION_STRING: postgresql://postgres:postgres@app-db:5432/db
    depends_on:
      app-db:
        condition: service_healthy
    ports:
      - "8000:8000"


